let sanskritDatabase = {};
let pratyayaDB = {}; 

// Hinglish/common word mappings - for casual English spellings of Hindi/Sanskrit words
const hinglishWordMap = {
    'ram': 'राम', 'krishna': 'कृष्ण', 'shiva': 'शिव', 'ganesh': 'गणेश',
    'hanuman': 'हनुमान', 'vishnu': 'विष्णु', 'brahma': 'ब्रह्मा',
    'agni': 'अग्नि', 'vayu': 'वायु', 'indra': 'इन्द्र', 'surya': 'सूर्य',
    'ganga': 'गङ्गा', 'yama': 'यम', 'kama': 'काम', 'dharma': 'धर्म',
    'karma': 'कर्म', 'yoga': 'योग', 'mantra': 'मन्त्र', 'veda': 'वेद',
    'rishi': 'ऋषि', 'guru': 'गुरु', 'pandit': 'पण्डित', 'swami': 'स्वामी',
    'bhagwan': 'भगवान', 'deva': 'देव', 'devi': 'देवी',
    'raja': 'राजा', 'rani': 'रानी', 'putra': 'पुत्र', 'kanya': 'कन्या',
    'griha': 'गृह', 'nagar': 'नगर', 'pura': 'पुर', 'desh': 'देश',
    'nadi': 'नदी', 'pani': 'पानी', 'aakash': 'आकाश', 'dharti': 'धरती',
    'mata': 'माता', 'pita': 'पिता', 'bhaai': 'भाई', 'behen': 'बहन',
    'mandir': 'मन्दिर', 'pustak': 'पुस्तक', 'shala': 'शाला',
    'vaidya': 'वैद्य', 'chikitsa': 'चिकित्सा', 'aushadhi': 'औषधि',
    'bhojan': 'भोजन', 'jal': 'जल', 'anna': 'अन्न', 'phool': 'फूल',
    'pav': 'पाव', 'kitab': 'किताब', 'kursi': 'कुर्सी',
    'darwaza': 'दरवाज़ा', 'khidki': 'खिड़की', 'chhatri': 'छतरी',
    'baaraat': 'बारात', 'shadi': 'शादी', 'tyohar': 'त्योहार',
    'sabha': 'सभा', 'samiti': 'समिति', 'sena': 'सेना',
    'rajya': 'राज्य', 'raj': 'राज', 'maharaja': 'महाराजा',
    'yuva': 'युवा', 'balak': 'बालक', 'stri': 'स्त्री',
    'purush': 'पुरुष', 'manushya': 'मनुष्य', 'jeev': 'जीव',
    'jeevan': 'जीवन', 'mrit': 'मृत', 'mrityu': 'मृत्यु',
    'sukh': 'सुख', 'dukh': 'दुख', 'prem': 'प्रेम', 'pyar': 'प्यार',
    'dosti': 'दोस्ती', 'saheli': 'सहेली', 'baba': 'बाबा',
    'acharya': 'आचार्य', 'vidwan': 'विद्वान', 'mahila': 'महिला',
    'nari': 'नारी', 'kumari': 'कुमारी', 'pati': 'पति', 'patni': 'पत्नी',
    'santan': 'सन्तान', 'kul': 'कुल', 'vansh': 'वंश', 'parivar': 'परिवार',
    'ghar': 'घर', 'makhan': 'मक्खन', 'dahi': 'दही',
    'chawal': 'चावल', 'roti': 'रोटी', 'dal': 'दाल', 'sabzi': 'सब्ज़ी',
    'phoolgobhi': 'फूलगोभी', 'pyaaz': 'प्याज़', 'adrak': 'अदरक',
    'lehsun': 'लहसुन', 'haldi': 'हल्दी', 'mirch': 'मिर्च',
    'namak': 'नमक', 'shakkar': 'शक्कर', 'chini': 'चीनी',
    'kapur': 'कपूर', 'agarbatti': 'अगरबत्ती', 'deepak': 'दीपक',
    'diya': 'दीया', 'pooja': 'पूजा', 'aarti': 'आरती', 'jaap': 'जाप',
    'tapasya': 'तपस्या', 'sadhana': 'साधना', 'ashram': 'आश्रम',
    'teerth': 'तीर्थ', 'kshetra': 'क्षेत्र', 'pavitra': 'पवित्र',
    'shuddh': 'शुद्ध', 'sundar': 'सुन्दर', 'khoobsurat': 'खूबसूरत',
    'bada': 'बड़ा', 'chota': 'छोटा', 'lamba': 'लंबा',
    'achha': 'अच्छा', 'bura': 'बुरा', 'tez': 'तेज', 'dheere': 'धीरे',
    'galat': 'गलत', 'sahi': 'सही', 'thik': 'ठीक',
    'haan': 'हाँ', 'nahin': 'नहीं', 'nahi': 'नहीं', 'ji': 'जी',
    'kya': 'क्या', 'kaise': 'कैसे', 'kab': 'कब', 'kahan': 'कहाँ',
    'kaun': 'कौन', 'kyon': 'क्यों', 'kitna': 'कितना',
    'mitr': 'मित्र', 'shatru': 'शत्रु', 'shishya': 'शिष्य',
    'pandita': 'पण्डिता', 'santan': 'सन्तान',
    'teerth': 'तीर्थ', 'sthal': 'स्थल',
    'sundarta': 'सुन्दरता', 'bara': 'बड़ा',
    'sakhi': 'सखी', 'tau': 'ताऊ', 'bua': 'बुआ',
    'nana': 'नाना', 'nani': 'नानी', 'dada': 'दादा', 'dadi': 'दादी',
    'fufa': 'फूफा', 'fufi': 'फूफी',
    'chacha': 'चाचा', 'chachi': 'चाची', 'mama': 'मामा', 'mausi': 'मौसी',
    'saas': 'सास', 'sasur': 'ससुर', 'behen': 'बहन', 'bhaai': 'भाई',
    'didi': 'दीदी', 'bhaiya': 'भैया',
    'swamiji': 'स्वामीजी', 'panditji': 'पण्डितजी',
    'maulana': 'मौलाना', 'babaji': 'बाबाजी',
    'yatra': 'यात्रा', 'darshan': 'दर्शन', 'prasad': 'प्रसाद',
    'bhajan': 'भजन', 'kirtan': 'कीर्तन', 'homa': 'होम',
    'yajna': 'यज्ञ', 'havan': 'हवन', 'upasana': 'उपासना',
    'bhakti': 'भक्ति', 'jnana': 'ज्ञान', 'vairagya': 'वैराग्य',
    'moksha': 'मोक्ष', 'nirvana': 'निर्वाण', 'samadhi': 'समाधि',
    'prana': 'प्राण', 'chakra': 'चक्र', 'kundalini': 'कुण्डलिनी',
    'tantra': 'तंत्र', 'mudra': 'मुद्रा', 'asana': 'आसन',
    'pranayam': 'प्राणायाम', 'dhyana': 'ध्यान',
    'siddhi': 'सिद्धि', 'shakti': 'शक्ति', 'shanti': 'शान्ति',
    'om': 'ॐ', 'swastika': 'स्वस्तिक', 'kalash': 'कलश',
    'purnakumbh': 'पूर्णकुंभ', 'toran': 'तोरण',
    'rangoli': 'रंगोली', 'alpana': 'अल्पना',
    'mehendi': 'मेहंदी', 'sindoor': 'सिन्दूर',
    'mangalsutra': 'मंगलसूत्र', 'bichhiya': 'बिछिया',
    'payal': 'पायल', 'kada': 'कड़ा', 'kangna': 'कंगन',
    'nath': 'नथ', 'laung': 'लौंग',
    'gopi': 'गोपी', 'radha': 'राधा',
    'arjun': 'अर्जुन', 'bheem': 'भीम', 'yudh': 'युद्ध',
    'dron': 'द्रोण', 'ashwathama': 'अश्वथामा', 'karna': 'कर्ण',
    'duryodhan': 'दुर्योधन', 'shakuni': 'शकुनि',
    'bhishma': 'भीष्म', 'parashuram': 'परशुराम',
    'ramayan': 'रामायण', 'mahabharat': 'महाभारत',
    'puran': 'पुराण', 'upanishad': 'उपनिषद',
    'bhagvadgita': 'भगवद्गीता', 'vedant': 'वेदांत',
    'mimansa': 'मीमांसा', 'nyaya': 'न्याय',
    'vaiseshik': 'वैशेषिक', 'samkhya': 'सांख्य',
    'yogasutra': 'योगसूत्र', 'ashtang': 'अष्टांग',
    'hath': 'हठ', 'kundalini': 'कुण्डलिनी',
    'chakra': 'चक्र', 'nadi': 'नाड़ी', 'prana': 'प्राण',
    'shushumna': 'सुषुम्णा', 'ida': 'इडा', 'pingla': 'पिङ्गला',
    'bindu': 'बिंदु', 'mandala': 'मण्डल', 'yantra': 'यंत्र',
    'mantra': 'मन्त्र', 'beej': 'बीज', 'bij': 'बीज',
    'siddha': 'सिद्ध', 'nath': 'नाथ', 'siddh': 'सिद्ध',
    'naga': 'नाग', 'yaksha': 'यक्ष', 'rakshas': 'राक्षस',
    'asura': 'असुर', 'danav': 'दानव', 'ravan': 'रावण',
    'meghnad': 'मेघनाद', 'kumbhkaran': 'कुम्भकरण',
    'vibhishan': 'विभीषण', 'shurpanakha': 'शूर्पणखा',
    'tulsidas': 'तुलसीदास', 'kabir': 'कबीर', 'meerabai': 'मीराबाई',
    'tukaram': 'तुकाराम', 'narsinh': 'नरसिंह', 'surdas': 'सूरदास',
    'chaitanya': 'चैतन्य', 'ramanuj': 'रामानुज', 'madhav': 'माधव',
    'adiguru': 'आदिगुरु', 'shankar': 'शंकर', 'ramkrishna': 'रामकृष्ण',
    'vivekanand': 'विवेकानंद', 'chinmayanand': 'चिन्मयानंद',
    'satya': 'सत्य', 'ahinsa': 'अहिंसा', 'karuna': 'करुणा',
    'daya': 'दया', 'kshama': 'क्षमा', 'dhairya': 'धैर्य',
    'virya': 'वीर्य', 'samta': 'समता', 'tyag': 'त्याग',
    'aparigraha': 'अपरिग्रह', 'asteya': 'अस्तेय', 'brahmacharya': 'ब्रह्मचर्य',
    'sauch': 'शौच', 'santosha': 'संतोष', 'tap': 'तप',
    'swadhyay': 'स्वाध्याय', 'ishwar': 'ईश्वरप्रणिधान',
    'yama': 'यम', 'niyam': 'नियम', 'asana': 'आसन',
    'pratyahar': 'प्रत्याहार', 'dharana': 'धारणा',
    'dhyana': 'ध्यान', 'samadhi': 'समाधि',
    'prakriti': 'प्रकृति', 'purusha': 'पुरुष',
    'triguna': 'त्रिगुण', 'sattva': 'सत्त्व', 'rajas': 'रजस्',
    'tamas': 'तमस्', 'maya': 'माया', 'avidya': 'अविद्या',
    'vidya': 'विद्या', 'moha': 'मोह', 'lobh': 'लोभ',
    'krodh': 'क्रोध', 'mada': 'मद', 'matsarya': 'मत्सर्य',
    'rag': 'राग', 'dwesh': 'द्वेष', 'bhay': 'भय',
    'vishad': 'विषाद', 'chinta': 'चिंता', 'udveg': 'उद्वेग',
    'nirvikar': 'निर्विकार', 'stithpragya': 'स्थितप्रज्ञ',
    'vairagya': 'वैराग्य', 'tyag': 'त्याग', 'sanyas': 'संन्यास',
    'grihasth': 'गृहस्थ', 'brahmachari': 'ब्रह्मचारी',
    'vanprasth': 'वानप्रस्थ', 'sanyasi': 'संन्यासी',
    'ashram': 'आश्रम', 'dharma': 'धर्म', 'artha': 'अर्थ',
    'kama': 'काम', 'moksha': 'मोक्ष', 'purushartha': 'पुरुषार्थ',
    'varna': 'वर्ण', 'ashram': 'आश्रम', 'samskara': 'संस्कार',
    'sanskara': 'संस्कार', 'upanayan': 'उपनयन',
    'yajnopavit': 'यज्ञोपवीत', 'grihya': 'गृह्य',
    'shrauta': 'श्रौत', 'smarta': 'स्मार्त',
    'agama': 'आगम', 'nigama': 'निगम',
    'tantr': 'तंत्र', 'yantra': 'यंत्र', 'mantra': 'मन्त्र',
    'pratishtha': 'प्रतिष्ठा', 'avahan': 'आवाहन',
    'shodash': 'षोडश', 'upachar': 'उपचार',
    'puja': 'पूजा', 'archana': 'अर्चना', 'stotra': 'स्तोत्र',
    'ashtakam': 'अष्टकम', 'sahasranam': 'सहस्रनाम',
    'chalisa': 'चालीसा', 'astak': 'अष्टक',
    'stavan': 'स्तवन', 'stuti': 'स्तुति',
    'vandana': 'वन्दना', 'namavali': 'नामावली',
    'kavach': 'कवच', 'argala': 'अर्गला',
    'kilak': 'किलक', 'samput': 'सम्पुट',
    'nyas': 'न्यास', 'mudra': 'मुद्रा',
    'mantra': 'मन्त्र', 'japa': 'जाप', 'homa': 'होम',
    'yajna': 'यज्ञ', 'dana': 'दान', 'dakshina': 'दक्षिणा',
    'bhiksha': 'भिक्षा', 'prasad': 'प्रसाद',
    'naivedya': 'नैवेद्य', 'bali': 'बलि',
    'tarpan': 'तर्पण', 'shraddha': 'श्राद्ध',
    'pind': 'पिंड', 'pret': 'प्रेत', 'pitru': 'पितृ',
    'dev': 'देव', 'pitru': 'पितृ', 'rishi': 'ऋषि',
    'manushya': 'मनुष्य', 'pashu': 'पशु', 'pakshi': 'पक्षी',
    'vriksha': 'वृक्ष', 'pushp': 'पुष्प', 'phool': 'फूल',
    'dhatu': 'धातु', 'pratyay': 'प्रत्यय',
    'sutra': 'सूत्र', 'vaky': 'वाक्य', 'shlok': 'श्लोक',
    'pady': 'पद्य', 'geet': 'गीत', 'bhajan': 'भजन',
    'kirtan': 'कीर्तन', 'stotra': 'स्तोत्र', 'ashtakam': 'अष्टकम',
    'sahasranam': 'सहस्रनाम', 'chalisa': 'चालीसा',
    'doha': 'दोहा', 'chaupai': 'चौपाई', 'kavit': 'कविता',
    'kavya': 'काव्य', 'mahakavya': 'महाकाव्य', 'khandakavya': 'खण्डकाव्य',
    'akhyayika': 'अख्यायिका', 'katha': 'कथा', 'prabandh': 'प्रबन्ध',
    'campu': 'चम्पू', 'sandesh': 'सन्देश', 'baramas': 'बारमास',
    'harikatha': 'हरिकथा', 'burrakatha': 'बुर्रकथा',
    'kirtan': 'कीर्तन', 'bhajan': 'भजन', 'namavali': 'नामावली',
    'sankirtan': 'संकीर्तन', 'nama': 'नाम', 'japa': 'जाप',
    'ajapa': 'अजाप', 'ajapajap': 'अजापजप', 'hridaya': 'हृदय',
    'manas': 'मनस्', 'buddhi': 'बुद्धि', 'chitta': 'चित्त',
    'ahankar': 'अहङ्कार', 'antahkarana': 'अन्तःकरण',
    'sukshma': 'सूक्ष्म', 'sthula': 'स्थूल',
    'karana': 'कारण', 'karya': 'कार्य',
    'nimitta': 'निमित्त', 'upaadana': 'उपादान',
    'sambandh': 'संबंध', 'vishay': 'विषय',
    'vishaya': 'विषय', 'alamban': 'आलम्बन',
    'ashray': 'आश्रय', 'adhisthan': 'अधिष्ठान',
    'shakti': 'शक्ति', 'shaktiman': 'शक्तिमान',
    'prabhav': 'प्रभाव', 'vaibhav': 'वैभव',
    'aishvarya': 'ऐश्वर्य', 'yash': 'यश', 'kirti': 'कीर्ति',
    'fame': 'कीर्ति', 'glory': 'यश', 'honor': 'सम्मान',
    'respect': 'सम्मान', 'dignity': 'गरिमा',
    'pride': 'गर्व', 'ego': 'अहङ्कार', 'humility': 'विनम्रता',
    'modesty': 'विनय', 'courtesy': 'विनय', 'politeness': 'विनय',
    'gratitude': 'कृतज्ञता', 'thankfulness': 'कृतज्ञता',
    'appreciation': 'प्रशंसा', 'admiration': 'प्रशंसा',
    'love': 'प्रेम', 'affection': 'स्नेह', 'fondness': 'राग',
    'attachment': 'आसक्ति', 'detachment': 'वैराग्य',
    'desire': 'इच्छा', 'craving': 'तृष्णा', 'longing': 'वसना',
    'passion': 'राग', 'anger': 'क्रोध', 'hatred': 'द्वेष',
    'aversion': 'द्वेष', 'dislike': 'अरुचि', 'disgust': 'घृणा',
    'fear': 'भय', 'terror': 'भीति', 'anxiety': 'चिंता',
    'worry': 'चिंता', 'tension': 'तनाव', 'stress': 'तनाव',
    'depression': 'विषाद', 'sadness': 'शोक', 'grief': 'शोक',
    'misery': 'दुःख', 'trouble': 'कष्ट', 'problem': 'समस्या',
    'difficulty': 'कठिनाई', 'obstacle': 'बाधा', 'hurdle': 'बाधा',
    'challenge': 'चुनौती', 'test': 'परीक्षा', 'trial': 'परीक्षा',
    'opportunity': 'अवसर', 'chance': 'मौका', 'possibility': 'संभावना',
    'hope': 'आशा', 'expectation': 'उम्मीद', 'belief': 'विश्वास',
    'faith': 'विश्वास', 'trust': 'विश्वास', 'confidence': 'आत्मविश्वास',
    'courage': 'साहस', 'bravery': 'वीरता', 'valor': 'वीरता',
    'heroism': 'वीरता', 'strength': 'बल', 'power': 'शक्ति',
    'energy': 'ऊर्जा', 'vitality': 'जीवनशक्ति', 'vigor': 'ताकत',
    'enthusiasm': 'उत्साह', 'zeal': 'उत्साह', 'passion': 'राग',
    'interest': 'रुचि', 'curiosity': 'जिज्ञासा', 'inquisitiveness': 'जिज्ञासा',
    'wisdom': 'ज्ञान', 'knowledge': 'ज्ञान', 'understanding': 'बोध',
    'intelligence': 'बुद्धि', 'intellect': 'बुद्धि', 'mind': 'मन',
    'consciousness': 'चेतना', 'awareness': 'ज्ञान', 'realization': 'अनुभव',
    'enlightenment': 'ज्ञान', 'awakening': 'जागरण', 'liberation': 'मोक्ष',
    'freedom': 'स्वतंत्रता', 'independence': 'स्वतंत्रता',
    'autonomy': 'स्वायत्तता', 'self': 'आत्मा', 'soul': 'आत्मा',
    'spirit': 'आत्मा', 'essence': 'सार', 'core': 'मूल',
    'root': 'मूल', 'base': 'आधार', 'foundation': 'नींव',
    'principle': 'सिद्धांत', 'rule': 'नियम', 'law': 'विधान',
    'duty': 'कर्तव्य', 'responsibility': 'दायित्व', 'obligation': 'बाध्यता',
    'right': 'अधिकार', 'privilege': 'विशेषाधिकार',
    'justice': 'न्याय', 'fairness': 'न्याय', 'equality': 'समानता',
    'equity': 'समानता', 'balance': 'संतुलन', 'harmony': 'सामंजस्य',
    'peace': 'शान्ति', 'tranquility': 'शांति', 'calm': 'शांत', 'shant': 'शांत', 'shaant': 'शांत',
    'silence': 'मौन', 'quiet': 'शांत', 'stillness': 'निष्क्रियता',
    'meditation': 'ध्यान', 'contemplation': 'ध्यान', 'reflection': 'चिंतन',
    'thought': 'विचार', 'idea': 'विचार', 'concept': 'अवधारणा',
    'notion': 'विचार', 'perception': 'अनुभव', 'view': 'दृष्टिकोण',
    'opinion': 'मत', 'belief': 'विश्वास', 'conviction': 'दृढ़विश्वास',
    'certainty': 'निश्चय', 'assurance': 'आश्वासन', 'guarantee': 'गारंटी',
    'promise': 'वादा', 'commitment': 'प्रतिबद्धता', 'dedication': 'समर्पण',
    'devotion': 'भक्ति', 'loyalty': 'निष्ठा', 'faithfulness': 'निष्ठा',
    'sincerity': 'ईमानदारी', 'honesty': 'ईमानदारी', 'truth': 'सत्य',
    'reality': 'वास्तविकता', 'fact': 'तथ्य', 'truth': 'सत्य',
    'actuality': 'वास्तविकता', 'existence': 'अस्तित्व', 'being': 'अस्तित्व',
    'life': 'जीवन', 'living': 'जीवन', 'existence': 'अस्तित्व',
    'nature': 'प्रकृति', 'world': 'विश्व', 'universe': 'ब्रह्मांड',
    'cosmos': 'ब्रह्मांड', 'creation': 'सृष्टि', 'destruction': 'लय',
    'preservation': 'संरक्षण', 'transformation': 'रूपांतरण',
    'change': 'परिवर्तन', 'evolution': 'विकास', 'growth': 'विकास',
    'progress': 'प्रगति', 'development': 'विकास', 'improvement': 'सुधार',
    'advancement': 'प्रगति', 'achievement': 'उपलब्धि', 'success': 'सफलता',
    'victory': 'विजय', 'triumph': 'विजय', 'conquest': 'विजय',
    'defeat': 'पराजय', 'loss': 'हानि', 'failure': 'असफलता',
    'mistake': 'गलती', 'error': 'त्रुटि', 'fault': 'दोष',
    'blame': 'दोष', 'accusation': 'आरोप', 'criticism': 'आलोचना',
    'complaint': 'शिकायत', 'grievance': 'शिकायत', 'problem': 'समस्या',
    'issue': 'मुद्दा', 'matter': 'बात', 'affair': 'बात',
    'subject': 'विषय', 'topic': 'विषय', 'theme': 'विषय',
    'title': 'शीर्षक', 'heading': 'शीर्षक', 'caption': 'विवरण',
    'label': 'लेबल', 'tag': 'टैग', 'mark': 'चिह्न',
    'sign': 'चिह्न', 'symbol': 'प्रतीक', 'emblem': 'चिह्न',
    'logo': 'लोगो', 'brand': 'ब्रांड', 'trademark': 'ट्रेडमार्क',
    'copyright': 'कॉपीराइट', 'patent': 'पेटेंट', 'license': 'लाइसेंस',
    'permission': 'अनुमति', 'consent': 'सहमति', 'approval': 'मंजूरी',
    'authorization': 'प्राधिकरण', 'validation': 'मान्यता', 'confirmation': 'पुष्टि',
    'verification': 'सत्यापन', 'authentication': 'प्रमाणीकरण',
    'identification': 'पहचान', 'recognition': 'पहचान', 'acknowledgment': 'स्वीकृति',
    'acceptance': 'स्वीकृति', 'approval': 'मंजूरी', 'endorsement': 'प्रवर्तन',
    'support': 'समर्थन', 'backing': 'समर्थन', 'sponsorship': 'प्रायोजन',
    'patronage': 'प्रायोजन', 'funding': 'वित्तपोषण', 'financing': 'वित्तपोषण',
    'investment': 'निवेश', 'capital': 'पूंजी', 'money': 'धन',
    'wealth': 'धन', 'riches': 'धन', 'fortune': 'भाग्य',
    'luck': 'भाग्य', 'chance': 'मौका', 'fate': 'भाग्य',
    'destiny': 'भाग्य', 'kismet': 'भाग्य', 'providence': 'प्रभुकृपा',
    'grace': 'कृपा', 'blessing': 'आशीर्वाद', 'boon': 'वर',
    'gift': 'उपहार', 'present': 'उपहार', 'offering': 'अर्पण',
    'donation': 'दान', 'charity': 'दान', 'philanthropy': 'सेवा',
    'service': 'सेवा', 'help': 'सहायता', 'assistance': 'सहायता',
    'aid': 'सहायता', 'relief': 'राहत', 'rescue': 'रक्षा',
    'protection': 'संरक्षण', 'defense': 'रक्षा', 'security': 'सुरक्षा',
    'safety': 'सुरक्षा', 'shelter': 'आश्रय', 'refuge': 'आश्रय',
    'sanctuary': 'अभय', 'haven': 'आश्रय', 'home': 'घर',
    'house': 'घर', 'residence': 'निवास', 'dwelling': 'निवास',
    'abode': 'निवास', 'place': 'स्थान', 'location': 'स्थान',
    'position': 'स्थिति', 'site': 'स्थान', 'spot': 'स्थान',
    'area': 'क्षेत्र', 'region': 'क्षेत्र', 'zone': 'क्षेत्र',
    'field': 'क्षेत्र', 'domain': 'क्षेत्र', 'sphere': 'क्षेत्र',
    'range': 'विस्तार', 'scope': 'दायरा', 'extent': 'सीमा',
    'limit': 'सीमा', 'boundary': 'सीमा', 'border': 'सीमा',
    'edge': 'किनारा', 'margin': 'हाशिया', 'side': 'पक्ष',
    'part': 'भाग', 'portion': 'भाग', 'section': 'खंड',
    'segment': 'खंड', 'division': 'विभाजन', 'category': 'श्रेणी',
    'class': 'वर्ग', 'type': 'प्रकार', 'kind': 'प्रकार',
    'sort': 'प्रकार', 'variety': 'विविधता', 'form': 'रूप',
    'shape': 'आकार', 'size': 'आकार', 'dimension': 'आयाम',
    'measure': 'माप', 'quantity': 'मात्रा', 'amount': 'राशि',
    'number': 'संख्या', 'count': 'गणना', 'total': 'कुल'
};

function joinSanskrit(text) {
    const vowelMap = { '्अ': '', '्आ': 'ा', '्इ': 'ि', '्ई': 'ी', '्उ': 'ु', '्ऊ': 'ू', '्ऋ': 'ृ', '्ए': 'े', '्ऐ': 'ै', '्ओ': 'ो', '्औ': 'ौ' };
    for (let [key, val] of Object.entries(vowelMap)) { text = text.split(key).join(val); }
    return text;
}

function autoGuna(d) {
    if (d.endsWith('ि') || d.endsWith('ी')) return d.slice(0, -1) + 'े';
}